bcgov/MOH-ALR

- .github/workflows/PR_Code_Deployment.yml
Fixing the workflow name and adding tagetusername
> PR Code Deployment GitHub Workflow Fix

- src-ui/main/default/flexipages/Residence_Record_Page.flexipage-meta.xml
Resolved following Defect on ALR - 303 - 
Class Type Field should be mandatory for all the Status values except for "PURR"
> ALR-303 Resolved Defect

- src/main/default/objects/Account/recordTypes/Registrant.recordType-meta.xml
Picklist Values Updated For Status Field on Registrant Record Type
> ALR-302 Picklist Values For Status Field

- src-access-mgmt/main/default/profiles/Admin.profile-meta.xml
- src-access-mgmt/main/default/profiles/EHIS Standard User.profile-meta.xml
- src-ui/main/default/flexipages/Business_License_Application_Record_Page.flexipage-meta.xml
- src-ui/main/default/layouts/Account-Residence Page Layout.layout-meta.xml
> ALR-243-45

- src/main/default/omniScripts/EHIS_ManageUnits_English_7.os-meta.xml
> ALR-436 (Omniscript)

- src-access-mgmt/main/default/permissionsetgroups/EHIS_ALR_Admin_PSG.permissionsetgroup-meta.xml
- src-access-mgmt/main/default/permissionsetgroups/EHIS_ALR_Investigator_PSG.permissionsetgroup-meta.xml
- src-access-mgmt/main/default/permissionsetgroups/EHIS_ALR_Leadership_PSG.permissionsetgroup-meta.xml
> ALR-89-PSG

- src/main/default/objects/RegulatoryTrxnFee/webLinks/Generate_Invoice.webLink-meta.xml
- src/main/default/objects/RegulatoryTrxnFee/webLinks/Generate_Receipt.webLink-meta.xml
> Revert "ALR-665 Added Invoice & Receipt Button"

- src/main/default/objects/PublicComplaint/listViews/My_Public_Complaints_Needing_Review.listView-meta.xml
> ALR-1215 changes commit

- src-access-mgmt/main/default/permissionsets/EHIS_Read_Visit_PS.permissionset-meta.xml
> ALR-1229 Changes Commit

- src/main/default/objects/Visit/listViews/My_Planned_Inspections.listView-meta.xml
> defect-ALR-1239 changes

- src/main/default/objects/Visit/listViews/My_Planned_Inspections.listView-meta.xml
> ALR-1239 Merge

- src/main/default/objects/Visit/listViews/My_Planned_Inspections.listView-meta.xml
> ALR-1239 Latest changes

- src/main/default/omniDataTransforms/DRToFetchCases_1.rpt-meta.xml
- src/main/default/omniDataTransforms/findCasesWithoutAcTA_1.rpt-meta.xml
> Defect-ALR-1238

- src/main/default/flows/InitialCmplianceInspCreation.flow-meta.xml
> ALR-1027 updates

- src-access-mgmt/main/default/permissionsets/EHIS_Admin_User_PS.permissionset-meta.xml
> Revert "ALR-1372"

- src-access-mgmt/main/default/permissionsets/EHIS_CRE_Assessment_Objects_PS.permissionset-meta.xml
EHIS assessment permission set , reports related permissions are removed
> update -1336 PS reports

- src-access-mgmt/main/default/permissionsetgroups/EHIS_ALR_SDPR_PSG.permissionsetgroup-meta.xml
- src/main/default/reports/SDPRReports/Residence_by_Registration_Status_hXn.report-meta.xml
- src/main/default/reports/SDPRReports/Residences_within_Region_9Wk.report-meta.xml
- src/main/default/sharingRules/Account.sharingRules-meta.xml
- src/main/default/sharingRules/AssessmentTask.sharingRules-meta.xml
- src/main/default/sharingRules/Case.sharingRules-meta.xml
- src/main/default/sharingRules/ComplaintCase.sharingRules-meta.xml
- src/main/default/sharingRules/InspectionType.sharingRules-meta.xml
- src/main/default/sharingRules/RegulatoryCodeViolation.sharingRules-meta.xml
- src/main/default/sharingRules/Visit.sharingRules-meta.xml
Edit permissions for SDPR persona
> ALR-1473.2

- src-access-mgmt/main/default/profiles/MOH Standard User.profile-meta.xml
Modified MOH Standard User Profile changes
> Modified MOH Standard User Profile changes

- src-access-mgmt/main/default/permissionsets/EHIS_Data_Analyst_User_Tab_PS.permissionset-meta.xml
- src-access-mgmt/main/default/permissionsets/EHIS_RE_Public_Complaints_PS.permissionset-meta.xml
Added FLS to 'is approval required' field & give access to 'Add Inspection task' button
> ALR-1582.1

- src/main/default/classes/ComplaintCaseTriggerTest.cls
Change in ComplaintCaseTriggerTest
> ALR 1616 changes

- ehis-source/ehis-ui/main/default/layouts/Account-Business Entity Page Layout.layout-meta.xml
> UATBug-EHIS-1214

- src-env-specific/dev/main/default/customMetadata/IDP_User_Registration_User_Mapping.ALR_Data_Investigator.md-meta.xml
- src-env-specific/production/main/default/customMetadata/IDP_User_Registration_User_Mapping.ALR_Data_Investigator.md-meta.xml
- src-env-specific/st/main/default/customMetadata/IDP_User_Registration_User_Mapping.ALR_Data_Investigator.md-meta.xml
- src-env-specific/uat/main/default/customMetadata/IDP_User_Registration_User_Mapping.ALR_Data_Investigator.md-meta.xml
- src/main/default/customMetadata/IDP_User_Registration_User_Mapping.ALR_Data_Investigator.md-meta.xml
Default Domain Updated as per the environment in their specific folders
> BCMOHAD-25342-1 Default Domain Updated

- ehis-source/core/main/default/Permissionsets/EHIS_Read_Account_PS.permissionset-meta.xml
- src-access-mgmt/main/default/permissionsets/EHIS_MMHA_Read_All_Public_Sector_Objects_PS.permissionset-meta.xml
- src-ui/main/default/flexipages/PublicComplaintCaseRecordPage.flexipage-meta.xml
- src-ui/main/default/flexipages/Registrant_Record_Page.flexipage-meta.xml
- src-ui/main/default/flexipages/ReportableIncidentCaseRecordPage.flexipage-meta.xml
- src-ui/main/default/flexipages/Residence_Record_Page.flexipage-meta.xml
> Feature-MMHAUserIssue

- src-access-mgmt/main/default/permissionsetgroups/EHIS_ALR_MMHA_PSG.permissionsetgroup-meta.xml
- src-ui/main/default/flexipages/PublicComplaintCaseRecordPage.flexipage-meta.xml
- src-ui/main/default/flexipages/ReportableIncidentCaseRecordPage.flexipage-meta.xml
- src-ui/main/default/flexipages/Requests_Inquiries_Case_Record_Page.flexipage-meta.xml
- src-ui/main/default/flexipages/Residence_Record_Page.flexipage-meta.xml
> Feature-ALR-1136

- src-ui/main/default/flexipages/Registrant_Record_Page.flexipage-meta.xml
- src-ui/main/default/flexipages/Residence_Record_Page.flexipage-meta.xml
> feature-ALR-1246

- src-ui/main/default/flexipages/Registrant_Record_Page.flexipage-meta.xml
- src-ui/main/default/flexipages/Residence_Record_Page.flexipage-meta.xml
ALR Requested Changes for Account LRP
> ALR Requested Changes for Account LRP

- src/main/default/lwc/showRegulatoryViolationRecords/showRegulatoryViolationRecords.js
Description
BCMOHAM-21446- Update LWC to fix issue with LWC not populating results
Fixes # (BCMOHAM-21446)
Type of change
[X] Bug fix (non-breaking change which fixes an issue)
[ ] New feature (non-breaking change which adds functionality)
[ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
Checklist:
My code follows the style guidelines of this project
[X] I have performed a self-review of my own code
[X]I have commented my code, particularly in hard-to-understand areas
[X] I have made corresponding changes to the documentation
[X]My changes generate no new warnings
[X] I have added tests that prove my fix is effective or that my feature works
[X] New and existing unit tests pass locally with my changes
[X]Any dependent changes have been …
> BCMOHAM-21446- Update LWC to fix issue with LWC not populating results

- .github/workflows/QA_Code_Deployment _Hotfix.yml
- .github/workflows/QA_Code_Deployment.yml
- .github/workflows/ST_Code_Deployment.yml
Switching workflows from ubuntu-latest to ubuntu 24.04
> BCMOHAM-21446 || Github tag creation issue

- .github/workflows/QA_Code_Deployment.yml
I have added +3 instead of +2 which we discussed in the call @cgijeffolsen
> BCMOHAD-27312-V1 || Adding +3 to the new tag in QA Deployment

- src/main/default/lwc/operationAssessmentRecords/operationAssessmentRecords.js
- src/main/default/lwc/showRegulatoryViolationRecords/showRegulatoryViolationRecords.js
- src/main/default/omniDataTransforms/DRUpdateRegCodeViolationRecords_1.rpt-meta.xml
- src/main/default/omniDataTransforms/DRUpdateScorewhenBlank_1.rpt-meta.xml
- src/main/default/omniDataTransforms/DRUpdateSingleScore_1.rpt-meta.xml
Reverting the changes made as part of the fix made for risk assessment process Issue
> BCMOHAD-27312

- src-env-specific/dev/main/default/customMetadata/IDP_User_Registration_User_Mapping.ALR_MMHA.md-meta.xml
- src-env-specific/dev/main/default/customMetadata/IDP_User_Registration_User_Mapping.ALR_SDPR.md-meta.xml
- src-env-specific/ehis/main/default/customMetadata/IDP_User_Registration_User_Mapping.ALR_MMHA.md-meta.xml
- src-env-specific/ehis/main/default/customMetadata/IDP_User_Registration_User_Mapping.ALR_SDPR.md-meta.xml
- src-env-specific/hotfixdev/main/default/customMetadata/IDP_User_Registration_User_Mapping.ALR_MMHA.md-meta.xml
- src-env-specific/hotfixdev/main/default/customMetadata/IDP_User_Registration_User_Mapping.ALR_SDPR.md-meta.xml
- src-env-specific/hotfixqa/main/default/IDP_User_Registration_User_Mapping.ALR_MMHA.md-meta.xml
- src-env-specific/hotfixqa/main/default/IDP_User_Registration_User_Mapping.ALR_SDPR.md-meta.xml
- src-env-specific/hotfixqa/main/default/customMetadata/IDP_User_Registration_User_Mapping.ALR_SDPR.md-meta.xml
- src-env-specific/production/main/default/customMetadata/IDP_User_Registration_User_Mapping.ALR_MMHA.md-meta.xml
- src-env-specific/production/main/default/customMetadata/IDP_User_Registration_User_Mapping.ALR_SDPR.md-meta.xml
- src-env-specific/qa/main/default/customMetadata/IDP_User_Registration_User_Mapping.ALR_MMHA.md-meta.xml
- src-env-specific/qa/main/default/customMetadata/IDP_User_Registration_User_Mapping.ALR_SDPR.md-meta.xml
- src-env-specific/st/main/default/customMetadata/IDP_User_Registration_User_Mapping.ALR_MMHA.md-meta.xml
- src-env-specific/st/main/default/customMetadata/IDP_User_Registration_User_Mapping.ALR_SDPR.md-meta.xml
- src-env-specific/uat/main/default/customMetadata/IDP_User_Registration_User_Mapping.ALR_MMHA.md-meta.xml
- src-env-specific/uat/main/default/customMetadata/IDP_User_Registration_User_Mapping.ALR_SDPR.md-meta.xml
- src/main/default/customMetadata/IDP_User_Registration_Permission_Set.ALR_MMHA_EHIS_EHIS_ALR_MMHA_PSG.md-meta.xml
- src/main/default/customMetadata/IDP_User_Registration_Permission_Set.ALR_SDPR_EHIS_ALR_SDPR_PSG.md-meta.xml
BCMOHAD-27532- Configuring custom metadata for ALR_MMHA and ALR_SDPR
> BCMOHAD-27532- Configuring custom metadata for ALR_MMHA and ALR_SDPR

- src/main/default/classes/MassEmailController.cls
Description:
BCMOHAM-22939-Refactoring code to remove queries inside loop
Ticket: BCMOHAM-22939
> BCMOHAM-22939-Refactoring code to remove queries inside loop

- src/main/default/classes/MassEmailController.cls
- src/main/default/lwc/renewalBlaTable/renewalBlaTable.js
DESCRIPTION:
========
BCMOHAM-22939- adding iteration to limit records processed
TICKET
=======
BCMOHAM-22939
> BCMOHAM-22939- adding iteration to limit records processed

- src/main/default/classes/MassEmailController.cls
- src/main/default/lwc/renewalBlaTable/renewalBlaTable.js
Description:
BCMOHAM-22939-  Refactoring code to remove queries inside loop and reducing number of records processed
Ticket: BCMOHAM-22939
> Bcmoham 22939 1 Refactoring code to remove queries inside loop and reducing number of records processed

- src/main/default/flows/Update_Last_Inspection_Date.flow-meta.xml
Description
=======
BCMOHAM-22598-Update Flow
Ticket
======
BCMOHAM-22598
POST DEPLOYMENT STEP
===============
Using DataLoader
1- Export Inspection(Visit) record using below query:
SELECT Id,status FROM Visit  where ActualVisitStartTime <> null and status='Completed'
2-Run Data Update on records extracted in step 1 using same extract.csv file on object Inspection(Visit)
> BCMOHAM-22598-Update Flow

- src/main/default/classes/ChangeAccountOwnerTest.cls
Updated the Test class for the code coverage
> BCMOHAM-22598-V1 || Updated the Test class

- .github/workflows/QA_Code_Deployment.yml
Removing test classes flag to unblock QA deployments. 
Next Actions: Recommended to spin up a new environment to ensure code coverage is sufficient prior to Production Release
> BCMOHAM-22598 || Update QA_Code_Deployment.yml

- .github/workflows/OpsQA Code Deployment.yml
Creating github flow for automatic deployments to OpsQA
> BCMOHAM-22383 || Create github action for automatic deployments to OpsQA

- .github/workflows/PR_Code_Deployment_Hotfix.yml
- .github/workflows/PR_Code_Validation_Hotfix.yml
PR to update ymls files to ensure the workflow to validate the branches is working as per the project folder changes.
> BCMOHAD-26599 || updating yml files

- bcgov-source/app-alr/main/default/classes/LateFeeManagementControllerBatchTest.cls
- bcgov-source/app-alr/main/default/classes/ManageUnitOmniServiceTest.cls
- bcgov-source/app-alr/main/default/classes/ScheduledEmailTriggerTest.cls
Description:BCMOHAD-28556-Update test classes
Ticket:BCMOHAD-28556
> BCMOHAD-28556-Update test classes

- bcgov-source/app-alr/main/default/classes/ManageUnitsControllerTest.cls
- bcgov-source/app-alr/main/default/classes/MassEmailControllerTest.cls
Description: BCMOHAD-28556-Improving test coverage
Ticket : BCMOHAD-28556
> BCMOHAD-28556-Improving test coverage

- bcgov-source/app-alr/main/default/classes/MassEmailController.cls
- bcgov-source/app-alr/main/default/lwc/lateFeeManagementTable/lateFeeManagementTable.html
- bcgov-source/app-alr/main/default/lwc/lateFeeManagementTable/lateFeeManagementTable.js
Description: BCMOHAD-28112-Refactor Code
Ticket: BCMOHAD-28112
PDS: NA
> BCMOHAD-28112-1-Refactor Code

- bcgov-source/app-alr/main/default/flows/Update_Last_Inspection_Date.flow-meta.xml
Description: BCMOHAM-23751-Update Flow to filter on Inspection Method instead of…
Ticket: BCMOHAM-23751
POST DEPLOYMENT STEP
Using DataLoader
1- Export Inspection(Visit) record using below query:
SELECT Id,status FROM Visit where ActualVisitStartTime <> null and status='Completed'
2-Run Data Update on records extracted in step 1 using same extract.csv file on object Inspection(Visit)
> BCMOHAM-23751-2-Update flow to use inspection method

- bcgov-source/app-phocs/main/default/flexipages/EHIS_Business_Entity_Record_Page.flexipage-meta.xml
phocs-1629: add the missing column/field into the related list
> phocs-1629: add Category L1 into Facility related list

- bcgov-source/app-alr/main/default/classes/MassEmailController.cls
Description: BCMOHAD-28694-cover scenario if no related contact exists
Ticket : BCMOHAD-28694
> BCMOHAD-28694-cover scenario if no related contact exists

- bcgov-source/app-alr/main/default/classes/LateFeeManagementControllerBatchTest.cls
- bcgov-source/app-alr/main/default/classes/ManageUnitOmniServiceTest.cls
- bcgov-source/app-alr/main/default/classes/ManageUnitsControllerTest.cls
- bcgov-source/app-alr/main/default/classes/MassEmailControllerTest.cls
- bcgov-source/app-alr/main/default/classes/ScheduledEmailTriggerTest.cls
@vishwanthagandloju  Please review the changes in code coverage. Once PR is approved, kindly merge it to dev and execute the deployment script with the Run Local Tests flag to ensure everything is functioning as expected.
> BCMOHAD-28556 || Code coverage changes

- bcgov-source/app-phocs/main/default/objects/BoardCertification/BoardCertification.object-meta.xml
- bcgov-source/app-phocs/main/default/permissionsets/EHIS_CRE_Group_Membership_PS.permissionset-meta.xml
> EHIS-1688-fix

- bcgov-source/app-phocs/main/default/flexipages/BLAEvaluationRecordPage.flexipage-meta.xml
- bcgov-source/app-phocs/main/default/flexipages/BLAOperatingPermitRecordPage.flexipage-meta.xml
> EHIS-380 Add New Inspection button back as it was overwritten

- bcgov-source/app-phocs/main/default/relationshipGraphDefinitions/EHIS_Water_Connections_Graph.relationshipGraphDefinition-meta.xml
DEFECT-PHOCS-EHIS-1729,1771fix
> DEFECT-PHOCS-EHIS-1729,1771fix

- bcgov-source/app-phocs/main/default/relationshipGraphDefinitions/EHIS_Water_Connections_Graph.relationshipGraphDefinition-meta.xml
EHIS-1729,EHIS-1771 Fix to dev
> EHIS-1729,EHIS-1771 Fix

- bcgov-source/app-alr/main/default/flows/Update_Owner_of_Inspection_task.flow-meta.xml
Description: BCMOHAM-25610-Update owner of regulatory code
Ticket : BCMOHAM-25610
POST DEPLOYMENT STEP
=====================
Run below attached script in debug/execute anonymous to update historical data:
[PDS-Script.txt](https://github.com/user-attachments/files/20442973/PDS-Script.txt)
> BCMOHAM-25610-Update owner of regulatory code

- bcgov-source/app-alr/main/default/classes/LateFeeManagementControllerBatchTest.cls
- bcgov-source/app-alr/main/default/sharingRules/Asset.sharingRules-meta.xml
Description:
BCMOHAM-25897- Adding Sharing Rule for Asset with SDPR users
Ticket:
BCMOHAM-25897
> BCMOHAM-25897- Adding Sharing Rule for Asset with SDPR users

- bcgov-source/app-alr/main/default/classes/ChangeAccountOwnerTest.cls
- bcgov-source/app-alr/main/default/classes/LateFeeManagementControllerBatchTest.cls
- bcgov-source/app-alr/main/default/classes/MassEmailControllerTest.cls
Description:
BCMOHAD-29029-ALR - Review and Update Test Classes
Ticket:
BCMOHAD-29029
> BCMOHAD-29029 -ALR - Review and Update Test Classes

- bcgov-source/app-alr/main/default/permissionsetgroups/EHIS_ALR_SDPR_PSG.permissionsetgroup-meta.xml
Description: BCMOHAD-29419-Updating PSG EHIS ALR SDPR PSG - adding omnistudio user PS
Ticket :BCMOHAD-29419
> BCMOHAD-29419-Updating PSG EHIS ALR SDPR PSG - adding omnistudio user PS

- bcgov-source/app-phocs/main/default/flexipages/PHOCSBusinessLicensePermitRecordPage.flexipage-meta.xml
- bcgov-source/app-phocs/main/default/flexipages/PHOCSExemptionsRecordPage.flexipage-meta.xml
- bcgov-source/core/main/default/objects/BusinessLicenseApplication/recordTypes/PHOCSExemptions.recordType-meta.xml
> Bugfix-EHIS-227

- bcgov-source/app-phocs/main/default/omniDataTransforms/DMPHOCSFoodSafetyRequisition_1.rpt-meta.xml
- bcgov-source/app-phocs/main/default/omniDataTransforms/DTPHOCSFoodSafetyRequisition_1.rpt-meta.xml
> omnichanges

- bcgov-source/app-phocs/main/default/flexipages/PHOCSFoodTestRequisitionRecordPage.flexipage-meta.xml
- bcgov-source/app-phocs/main/default/profiles/EHIS Standard User.profile-meta.xml
> EHIS-2391-bugfix
